### ISSUE TITLE
Detect incompatibility and raise a relevant exception

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/client-python#55] opened 2019-07-15 12:25 UTC
## Problem to Solve

When there is an incompatibility between Client Python and the running Grakn Server, the exception thrown by the client seems unrelated to the real cause of the problem. In fact, the error message may even be incorrect, given that the keyspace does exist with the given name.

## Current Workaround

If encountering this exception for the first time, only searching the web or asking the community can lead the user to the solution.

## Proposed Solution

Have Client Python to identify the incompatibility and throw an exception with a helpful message. e.g. `Client Python version 1.5.3 does not support the running Grakn Core server. Please refer to the documentation of client Python to ensure compatibility.`

## Additional Information

N/A

**Comment by alexjpwalker** [comment] 2021-04-06 14:30
Closing as a duplicate of https://github.com/graknlabs/client-java/issues/25 (one issue that we propagate to all clients is enough)

**Closed by alexjpwalker** 2021-04-06 14:30 UTC
Labels: type: feature
